name: Abastractions.Nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: RepositoryFramework
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.0
        with:
          dotnet-version: ${{ secrets.NET_VERSION }}
          path: src/RepositoryFramework.Abstractions/RepositoryFramework.Abstractions.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}