name: Api.Client.Nuget
on:
  push:
    branches:
      - master
    paths:
      - src/RepositoryFramework.Api.Client/**
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: RepositoryFramework
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: ${{ secrets.NET_VERSION }}
          path: src/RepositoryFramework.Api.Client/RepositoryFramework.Api.Client.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}