name: Web.Components
on:
  push:
    branches:
      - master
    paths:
      - src/RepositoryFramework.Web/RepositoryFramework.Web.Components/**
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: RepositoryFramework
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v.1.0.2
        with:
          dotnet-version: "7.x"
          path: src/RepositoryFramework.Web/RepositoryFramework.Web.Components/RepositoryFramework.Web.Components.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}